alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '
alias gt='git tag'
alias gh='git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short'
alias gr='git reset HEAD'
alias grvh='git reverd HEAD'
alias grv='git reverd'
alias gst='git stash'
alias gsp='git stash pop'
alias gm='git merge'
alias gp='git pull'
alias p='git push'